# Purpose: This file is used for check application health.

# Name of the workflow
name: Application Status

on:
  push:
    branches:
      - main  # Trigger the workflow when a push event occurs on the main branch

jobs:
  build: # Define the "build" job
    runs-on: ubuntu-latest # Run the job on the latest version of Ubuntu
    steps: # List of steps to execute within the job
      - name: Update package cache # Step to update the package cache
        run: sudo apt-get update

      - name: Checkout code # Step to check out the code from the repository
        uses: actions/checkout@v3

      - name: Set up Java # Step to set up the Java environment
        uses: actions/setup-java@v3
        with:
          java-version: 17 # Specify Java 17 as the version
          distribution: 'zulu' # Use the 'zulu' distribution of Java

      - name: Install Maven # Step to install Maven
        run: sudo apt-get install -y maven


      - name: Copy configuration.properties file from template # Step to create a new 'configuration.properties' file by copying the 'template-configuration.properties'
        run: cp sample_configuration.properties configuration.properties

      - name: Replace api.url in configuration.properties # Step to replace the placeholder api.url in configuration.properties
        run: sed 's|'{API_URL}'|'${{ secrets.AYS_API_URL }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace database.url in configuration.properties # Step to replace the placeholder database.url in configuration.properties
        run: sed 's|'{DATABASE_URL}'|'${{ secrets.AYS_DATABASE_URL }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace database.username in configuration.properties # Step to replace the placeholder database.username in configuration.properties
        run: sed 's|'{DATABASE_USERNAME}'|'${{ secrets.AYS_DATABASE_USERNAME }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace database.password in configuration.properties # Step to replace the placeholder database.password in configuration.properties
        run: sed 's|'{DATABASE_PASSWORD}'|'${{ secrets.AYS_DATABASE_PASSWORD }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace afet_yonetim_sistemi.admin.email_address in configuration.properties # Step to replace the placeholder afet_yonetim_sistemi.admin.email_address in configuration.properties
        run: sed 's|'{AFET_YONETIM_SISTEMI_ADMIN_EMAIL_ADDRESS}'|'${{ secrets.AYS_AFET_YONETIM_SISTEMI_ADMIN_EMAIL_ADDRESS }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace afet_yonetim_sistemi.admin.password in configuration.properties # Step to replace the placeholder afet_yonetim_sistemi.admin.password in configuration.properties
        run: sed 's|'{AFET_YONETIM_SISTEMI_ADMIN_PASSWORD}'|'${{ secrets.AYS_AFET_YONETIM_SISTEMI_ADMIN_PASSWORD }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace volunteer_foundation.admin.emailAddress in configuration.properties # Step to replace the placeholder volunteer_foundation.admin.email_address in configuration.properties
        run: sed 's|'{VOLUNTEER_FOUNDATION_ADMIN_EMAIL_ADDRESS}'|'${{ secrets.AYS_VOLUNTEER_FOUNDATION_ADMIN_EMAIL_ADDRESS }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace volunteer_foundation.admin.password in configuration.properties # Step to replace the placeholder institution_one.admin_user_one.password in configuration.properties
        run: sed 's|'{VOLUNTEER_FOUNDATION_ADMIN_PASSWORD}'|'${{ secrets.AYS_VOLUNTEER_FOUNDATION_ADMIN_PASSWORD }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace disaster_foundation.admin.email_address in configuration.properties # Step to replace the placeholder disaster_foundation.admin.email_address in configuration.properties
        run: sed 's|'{DISASTER_FOUNDATION_ADMIN_EMAIL_ADDRESS}'|'${{ secrets.DISASTER_FOUNDATION_ADMIN_EMAIL_ADDRESS }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace disaster_foundation.admin.password in configuration.properties # Step to replace the placeholder disaster_foundation.adminpassword in configuration.properties
        run: sed 's|'{DISASTER_FOUNDATION_ADMIN_PASSWORD}'|'${{ secrets.AYS_DISASTER_FOUNDATION_ADMIN_PASSWORD }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace test_foundation.admin.email_address in configuration.properties # Step to replace the placeholder test_foundation.admin.email_address in configuration.properties
        run: sed 's|'{TEST_FOUNDATION_ADMIN_EMAIL_ADDRESS}'|'${{ secrets.AYS_TEST_FOUNDATION_ADMIN_EMAIL_ADDRESS }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace test_foundation.admin.password in configuration.properties # Step to replace the placeholder test_foundation.admin.password in configuration.properties
        run: sed 's|'{TEST_FOUNDATION_ADMIN_PASSWORD}'|'${{ secrets.AYS_TEST_FOUNDATION_ADMIN_PASSWORD }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace disaster_foundation.user.emailAddress in configuration.properties # Step to replace the placeholder disaster_foundation.user.email_address in configuration.properties
        run: sed 's|'{DISASTER_FOUNDATION_USER_EMAIL_ADDRESS}'|'${{ secrets.AYS_DISASTER_FOUNDATION_USER_EMAIL_ADDRESS }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace disaster_foundation.user.password in configuration.properties # Step to replace the placeholder disaster_foundation.user.password in configuration.properties
        run: sed 's|'{DISASTER_FOUNDATION_USER_PASSWORD}'|'${{ secrets.AYS_DISASTER_FOUNDATION_USER_PASSWORD }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace afet_yonetim_sistemi.id in configuration.properties # Step to replace the placeholder afet_yonetim_sistemi.id in configuration.properties
        run: sed 's|'{AFET_YONETIM_SISTEMI_ID}'|'${{ secrets.AYS_AFET_YONETIM_SISTEMI_ID }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace volunteer_foundation.id in configuration.properties # Step to replace the placeholder volunteer_foundation.id in configuration.properties
        run: sed 's|'{VOLUNTEER_FOUNDATION_ID}'|'${{ secrets.AYS_VOLUNTEER_FOUNDATION_ID }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace disaster_foundation.id in configuration.properties # Step to replace the placeholder disaster_foundation.id in configuration.properties
        run: sed 's|'{DISASTER_FOUNDATION_ID}'|'${{ secrets.AYS_DISASTER_FOUNDATION_ID }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties

      - name: Replace test_foundation.id in configuration.properties # Step to replace the placeholder disaster_foundation.id in configuration.properties
        run: sed 's|'{TEST_FOUNDATION_ID}'|'${{ secrets.AYS_TEST_FOUNDATION_ID }}'|g' configuration.properties >> temp_configuration.properties ; rm configuration.properties ; mv temp_configuration.properties configuration.properties


      - name: Build with Maven # Step to build the project with Maven
        run: mvn clean test -P weekly
