# Purpose: This file is used to run the tests when a pull request is opened, reopened, synchronized, ready for review, or unlocked.

# Name of the workflow
name: Pull Request Checker

# Trigger the workflow when various types of pull request events occur
on:
  pull_request:
    types:
      - opened # triggers the workflow when a pull request is opened.
      - reopened # triggers the workflow when a pull request is reopened after being closed.
      - synchronize # triggers the workflow when a pull request is synchronized (changes are pushed to the branch associated with the pull request)
      - ready_for_review # triggers the workflow when a pull request is marked as ready for review
      - unlocked # triggers the workflow when a previously locked pull request is unlocked

jobs:
  initialize: # Define the "initialize" job
    runs-on: ubuntu-latest # Run the job on the latest version of Ubuntu
    steps: # List of steps to execute within the job
      - name: Checkout code # Step to check out the code from the repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/initialize-environment
        with:
          SSH_ENABLED: ${{ vars.SSH_ENABLED }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ vars.SSH_USERNAME }}
          SSH_PRIVATE_KEY_PEM: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          AYS_API_URL: ${{ secrets.AYS_API_URL }}
          AYS_DATABASE_URL: ${{ secrets.AYS_DATABASE_URL }}
          AYS_DATABASE_USERNAME: ${{ vars.AYS_DATABASE_USERNAME }}
          AYS_DATABASE_PASSWORD: ${{ secrets.AYS_DATABASE_PASSWORD }}
          AYS_TEST_DISASTER_FOUNDATION_ID: ${{ vars.AYS_TEST_DISASTER_FOUNDATION_ID }}
          AYS_TEST_DISASTER_FOUNDATION_ADMIN_EMAIL_ADDRESS: ${{ vars.AYS_TEST_DISASTER_FOUNDATION_ADMIN_EMAIL_ADDRESS }}
          AYS_TEST_DISASTER_FOUNDATION_ADMIN_PASSWORD: ${{ secrets.AYS_TEST_DISASTER_FOUNDATION_ADMIN_PASSWORD }}
          AYS_TEST_DISASTER_FOUNDATION_USER_EMAIL_ADDRESS: ${{ vars.AYS_TEST_DISASTER_FOUNDATION_USER_EMAIL_ADDRESS }}
          AYS_TEST_DISASTER_FOUNDATION_USER_PASSWORD: ${{ secrets.AYS_TEST_DISASTER_FOUNDATION_USER_PASSWORD }}
          AYS_TEST_VOLUNTEER_FOUNDATION_ID: ${{ vars.AYS_TEST_VOLUNTEER_FOUNDATION_ID }}
          AYS_TEST_VOLUNTEER_FOUNDATION_SUPER_ADMIN_EMAIL_ADDRESS: ${{ vars.AYS_TEST_VOLUNTEER_FOUNDATION_SUPER_ADMIN_EMAIL_ADDRESS }}
          AYS_TEST_VOLUNTEER_FOUNDATION_SUPER_ADMIN_PASSWORD: ${{ secrets.AYS_TEST_VOLUNTEER_FOUNDATION_SUPER_ADMIN_PASSWORD }}
          AYS_TEST_VOLUNTEER_FOUNDATION_ADMIN_EMAIL_ADDRESS: ${{ vars.AYS_TEST_VOLUNTEER_FOUNDATION_ADMIN_EMAIL_ADDRESS }}
          AYS_TEST_VOLUNTEER_FOUNDATION_ADMIN_PASSWORD: ${{ secrets.AYS_TEST_VOLUNTEER_FOUNDATION_ADMIN_PASSWORD }}
          AYS_TEST_VOLUNTEER_FOUNDATION_USER_EMAIL_ADDRESS: ${{ vars.AYS_TEST_VOLUNTEER_FOUNDATION_USER_EMAIL_ADDRESS }}
          AYS_TEST_VOLUNTEER_FOUNDATION_USER_PASSWORD: ${{ secrets.AYS_TEST_VOLUNTEER_FOUNDATION_USER_PASSWORD }}

  test:
    runs-on: ubuntu-latest
    needs: initialize

    steps:
      - name: Checkout code # Step to check out the code from the repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/initialize-environment
        with:
          SSH_ENABLED: ${{ vars.SSH_ENABLED }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ vars.SSH_USERNAME }}
          SSH_PRIVATE_KEY_PEM: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          AYS_API_URL: ${{ secrets.AYS_API_URL }}
          AYS_DATABASE_URL: ${{ secrets.AYS_DATABASE_URL }}
          AYS_DATABASE_USERNAME: ${{ vars.AYS_DATABASE_USERNAME }}
          AYS_DATABASE_PASSWORD: ${{ secrets.AYS_DATABASE_PASSWORD }}
          AYS_TEST_DISASTER_FOUNDATION_ID: ${{ vars.AYS_TEST_DISASTER_FOUNDATION_ID }}
          AYS_TEST_DISASTER_FOUNDATION_ADMIN_EMAIL_ADDRESS: ${{ vars.AYS_TEST_DISASTER_FOUNDATION_ADMIN_EMAIL_ADDRESS }}
          AYS_TEST_DISASTER_FOUNDATION_ADMIN_PASSWORD: ${{ secrets.AYS_TEST_DISASTER_FOUNDATION_ADMIN_PASSWORD }}
          AYS_TEST_DISASTER_FOUNDATION_USER_EMAIL_ADDRESS: ${{ vars.AYS_TEST_DISASTER_FOUNDATION_USER_EMAIL_ADDRESS }}
          AYS_TEST_DISASTER_FOUNDATION_USER_PASSWORD: ${{ secrets.AYS_TEST_DISASTER_FOUNDATION_USER_PASSWORD }}
          AYS_TEST_VOLUNTEER_FOUNDATION_ID: ${{ vars.AYS_TEST_VOLUNTEER_FOUNDATION_ID }}
          AYS_TEST_VOLUNTEER_FOUNDATION_SUPER_ADMIN_EMAIL_ADDRESS: ${{ vars.AYS_TEST_VOLUNTEER_FOUNDATION_SUPER_ADMIN_EMAIL_ADDRESS }}
          AYS_TEST_VOLUNTEER_FOUNDATION_SUPER_ADMIN_PASSWORD: ${{ secrets.AYS_TEST_VOLUNTEER_FOUNDATION_SUPER_ADMIN_PASSWORD }}
          AYS_TEST_VOLUNTEER_FOUNDATION_ADMIN_EMAIL_ADDRESS: ${{ vars.AYS_TEST_VOLUNTEER_FOUNDATION_ADMIN_EMAIL_ADDRESS }}
          AYS_TEST_VOLUNTEER_FOUNDATION_ADMIN_PASSWORD: ${{ secrets.AYS_TEST_VOLUNTEER_FOUNDATION_ADMIN_PASSWORD }}
          AYS_TEST_VOLUNTEER_FOUNDATION_USER_EMAIL_ADDRESS: ${{ vars.AYS_TEST_VOLUNTEER_FOUNDATION_USER_EMAIL_ADDRESS }}
          AYS_TEST_VOLUNTEER_FOUNDATION_USER_PASSWORD: ${{ secrets.AYS_TEST_VOLUNTEER_FOUNDATION_USER_PASSWORD }}

      - name: Test with Maven # Step to start to test the project with Maven
        run: mvn clean test -P weekly
